feat: adds queries and script
RyeidHanif/Covid_Queries pull request #1
Opened 2024-07-24 08:43 UTC by RyeidHanif

2024-07-24 10:33 UTC, ahmed-arb requested changes
We don't really need to download the files first on drive. You can just load them in memory with [StringIO](https://www.geeksforgeeks.org/stringio-module-in-python/) and inject them. Your main should handle both downloading and injection. Also, try to do this task without pandas; use a class to store each row.

2024-07-24 10:33 UTC, ahmed-arb commented on main.py
> +from context_man import ContextManagerDB
Please remove the unused imports.

2024-07-24 10:33 UTC, ahmed-arb commented on injection.py
> +    ]
Again, variables that do no change on different instances should not be instance variables.

2024-07-24 10:33 UTC, ahmed-arb commented on downloading.py
> +local_directory = 'covid_files'
Store constants like these in a separate file constants.py

2024-07-24 10:33 UTC, ahmed-arb commented on injection.py
> +            print("Creating table {}".format(Table), "\n")
Explore [logging](https://docs.python.org/3/library/logging.html) instead of print statements.

2024-07-24 10:33 UTC, ahmed-arb commented on injection.py
> +        cols_drop = ["FIPS", "Admin2", "Lat", "Long_", "Combined_Key"]
Have you verified that these columns are empty in all files?

2024-07-24 10:33 UTC, ahmed-arb commented on injection.py
> +                            print("an error occurred ", e)
Are these two exceptions here necessary?

2024-07-24 10:33 UTC, ahmed-arb commented on context_man.py
> +        "database": "covid_stats_db"
These variables should be passed through the parameters.

2024-07-24 11:08 UTC, RyeidHanif commented on injection.py
> +                            print("an error occurred ", e)
kind of because for the isna one , will skip over anydates which arent there , which would otherwise throw the NaT error . for index 0 or 1 just to be safe i added it because thhe program was counting the column headers in the csv files as line 1 for some reason

2024-07-26 08:29 UTC, ahmed-arb requested changes
Your code base is shaping up. Let's improve it further.

2024-07-26 08:29 UTC, ahmed-arb commented on main.py
> +    print(f"an error occurred: {e}")
Try to catch specific exceptions and give appropriate feedback. Also, log the error instead of printing it.

2024-07-26 08:29 UTC, ahmed-arb commented on injector.py
> +from row_class import CovidRowHandler
Please remove the unused imports

2024-07-26 08:29 UTC, ahmed-arb commented on injector.py
> +logging.basicConfig(level=logging.INFO)
Don't we need logging in multiple module through out the project? Make a separate module to setup logger and have all other modules import logger from it.

2024-07-26 08:29 UTC, ahmed-arb commented on injector.py
> +    columns_str = ", ".join(cols_needed)
This should be the responsibility of `CovidRowHandler`

2024-07-26 08:29 UTC, ahmed-arb commented on injector.py
> +                        )
Explore [class methods](https://www.geeksforgeeks.org/classmethod-in-python/) in python and improve this by utilizing a class method.

2024-07-26 08:29 UTC, ahmed-arb commented on injector.py
> +                if ".csv" in file_name:
Can we not achieve the same behavior with the following code?
```suggestion
            if not file_name.endswith(".csv"):
                continue
```

2024-07-26 08:29 UTC, ahmed-arb commented on injector.py
> +        """
I think for downloading we should have a separate class, so that we can break this gigantic function into smaller ones. Also, explore and utilize [generator functions](https://www.geeksforgeeks.org/generators-in-python/) in Python.

2024-07-26 08:29 UTC, ahmed-arb commented on injector.py
> +                logger.error("Error message: %s", err)
This try-catch should be the responsibility of our context manager class. Since down the line, we may have to execute a lot more queries and we would have to duplicate this code everytime.

2024-07-26 08:29 UTC, ahmed-arb commented on context_man.py
> +        return self.cnx, self.cursor
We can just return `self` here.

2024-07-26 08:29 UTC, ahmed-arb commented on injector.py
> +                print(f"Batch {i // batch_size + 1} inserted successfully")
Batching and using `executemany` is excellent thinking. Well done.

2024-07-26 08:29 UTC, ahmed-arb commented on injector.py
> +                obj.Case_Fatality_Ratio,
As discussed before, we can utilize the `__dir__` method for this.

2024-07-26 08:29 UTC, ahmed-arb commented on Sqlqueries.py
> +columns_str = ", ".join(cols_needed)
Why do 3 modules have their own copies of this information?

2024-07-26 08:29 UTC, ahmed-arb commented on Sqlqueries.py
> +        "CONSTRAINT unique_cols UNIQUE (Country_Region, Province_State, Last_Update)"
Column names should be lower case.

2024-07-26 08:56 UTC, RyeidHanif commented on injector.py
> +                print(f"Batch {i // batch_size + 1} inserted successfully")
thank you !

2024-09-05 16:51 UTC, merged